workflows:
  ios-simulator:
    name: iOS Simulator Build
    instance_type: mac_mini_m2
    max_build_duration: 30

    environment:
      flutter: stable
      xcode: latest

    scripts:
      - name: Create .env file
        script: echo "$ENV_FILE" > $CM_BUILD_DIR/.env

      - name: Get Flutter packages
        script: flutter pub get

      - name: Install CocoaPods
        script: |
          cd ios
          pod install

      - name: Build for iOS Simulator
        script: |
          flutter build ios --simulator --debug --no-codesign

      - name: Compress .app bundle
        script: |
          cd build/ios/iphonesimulator
          zip -r Runner.app.zip Runner.app

    artifacts:
      - build/ios/iphonesimulator/Runner.app.zip
